### ISSUE TITLE
Ошибка FLOOD_WAIT_84900 после пара десятков запросов

### ISSUE THREAD

**Issue by dmitrypisanko** [xtrime-ru/TelegramRSS#11]
Приветствую, получают ошибку после пары десятков запросов через локальный сервер. В то же время если тащить данные через https://tg.i-c-a.su то все нормально. 

Не подскажите как избавиться от этой проблемы?

**Comment by xtrime-ru** [comment]
FLOOD_WAIT_84900 - это ошибка которую отдает телеграмм, когда количество запросов слишком большое (не типичное) для данного аккаунта. 84900 - это количество секунд до снятия ограничения. 

Обычно такая проблема возникает когда много обращений к новым каналам, которых нет в кеше. При этом обращения к каналам которые есть в кеше продолжают работать. 

Итого: нужно постепенно "прогревать" кеш и/или реже обращаться к новым каналам.

**Comment by dmitrypisanko** [comment]
Понял, я так понял на вашем сервисе кэш прогрет, так потому такая ошибка и не возникает. Спасибо, буду думать как прогреть.

**Comment by livxbox5** [comment]
FLOOD_WAIT_25362 что делать?

**Comment by xtrime-ru** [comment]
> FLOOD_WAIT_25362 что делать?

Ждать 25 тысяч секунд. 
Это ошибка от Telegram, скорее всего за получение данных по юзерам без прогретого кеша. 
Важно не очищать базу данных TelegramApiServer, тогда кеш данных о username будет в базе и не будет запрашиваться из telegram.
