### ISSUE TITLE
Не загружается картинка, бесконечное открытие страницы

### ISSUE THREAD

**Issue by YAMER1** [xtrime-ru/TelegramRSS#20]
Здравствуйте, не подгружается картинка, если её открывать по /media/channel_name/11/preview/thumb.jpeg, то она открывается бесконечно долго и зависает. Причём та картинка, которая взята из url чужого сайта, когда у поста нету картинки, но есть ссылка, а если картинка из самого поста телеграм, то с ней всё нормально. Почему так? Подскажите, пожалуйста, как можно исправить.

**Comment by YAMER1** [comment]
Хотя от типа картинки это не зависит, из ссылки она или нет. Вроде зависит от канала, у другого канала не зависает картинка в бесконечной загрузке, а у других зависает. От чего же это зависит...

**Comment by xtrime-ru** [comment]
Привет! Пришли пример канал в котором возникают проблемы? Это старый баг, в библиотеке MadelineProto, который не удается пока стабильно воспроизводить и поэтому сложно починить. 

Обычно через какое то время картинки с проблемных каналов/постов начинают работать.

**Comment by YAMER1** [comment]
> Привет! Пришли пример канала в котором возникают проблемы? Это старый баг, в библиотеке MadelineProto, который не удается пока стабильно воспроизводить и поэтому сложно починить.
> 
> Обычно через какое то время картинки с проблемных каналов/постов начинают работать.

После обновления и перезагрузок всё заработало. Потом проблема встречалась изредко и вроде решалась перезагрузкой.
